---
- name: use apache_vhost role playbook
  hosts: node2
  collections:
    - jboivie.apache_vhost_collection
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - apache_vhost

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'
