---
- name: Add centos-stream-template-clone to controller inventory
  hosts: localhost
  become: false
  gather_facts: false
  
  tasks:
  - name: Add host centos-stream-template-clone
    awx.awx.host:
      name: centos-stream-template-clone
      description: ""
      inventory: "Home Inventory"
      state: present
      variables:
        ansible_host: "{{ centos_clone_ip }}"
