---
- name: Provision CentOS VM for dev environment
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Clone the "centos-stream-template" VM
    ansible.builtin.shell:
      cmd: /usr/local/bin/prlctl clone centos-stream-template --name centos-stream-template-clone
  - name: Start the new VM
    ansible.builtin.shell:
      cmd: /usr/local/bin/prlctl start centos-stream-template-clone
  - name: Wait 20s for VM to start
    wait_for:
      timeout: 20
    delegate_to: localhost
  - name: Get IP address of centos-stream-template-clone
    ansible.builtin.shell:
      cmd: /usr/local/bin/prlctl exec "centos-stream-template-clone" ip -4 -br addr show enp0s5 | awk '{print $3}' | cut -d / -f 1
    register: clone_ip
  - name: IP address of centos-stream-template-clone
    ansible.builtin.debug:
      msg: "{{ clone_ip.stdout }}"
