---
- name: Provision CentOS VM for dev environment
  hosts: MacBook-Pro
  become: yes
  gather_facts: false

  tasks:
  - name: Clone the "centos-stream-template" VM
    ansible.builtin.shell:
      cmd: prlctl clone centos-stream-template --name centos-stream-template-clone
  - name: Start the new VM
    ansible.builtin.shell:
      cmd: prlctl start centos-stream-template-clone
