---
- name: Install code-server, setup Git
  hosts: "{{ centos_hostname }}"
  become: yes
  gather_facts: false
  vars:
    the_secret: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                33376537353436386161653735313961633334326138386563313433343963343332653562653934
                3461613838343433386264396233663331363137376235660a303063666464343063663634323735
                64656431326239326163643766363061613533343134643335623135623664616232393835353765
                3430383538343165350a653938616663633236376231383562666665303636343230613636663633
                38323636383637646239373236633963333434313930316538393962366132366363363534393732
                6634653863346565643062386437643936376465663534393438
    registry_pw: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                30373733333732636662313737666639323235626132303261316462333632316332393236663635
                3933323036333630363535336438613837333931306161390a346436616333343631363762316161
                62373161613136383962633864313161336461303161633136386565633334646636333731353236
                6236636233353530360a303463373136343164303539396566313633306366653632333336633464
                65333166653538346166663761303465653737646334373263323162643539666438
  tasks:
  - name: "Set a Linux hostname to {{ centos_hostname }}"
    ansible.builtin.hostname:
      name: "{{ centos_hostname }}"
      use: systemd
  - name: "Add the user {{ dev_username }}"
    ansible.builtin.user:
      name: "{{ dev_username }}"
      groups: wheel
      password: "{{ requested_password|password_hash('sha512') }}"
  - name: Generate private key for root
    ansible.builtin.user:
      name: root
      generate_ssh_key: yes
  - name: Create projects directory
    ansible.builtin.file:
      path: "/home/{{ dev_username }}/projects"
      state: directory
      owner: "{{ dev_username }}"
      mode: '0755'
  - name: Download and Install code-server
    ansible.builtin.shell:
      cmd: curl -fsSL https://code-server.dev/install.sh | sh
  - name: Enable code-server
    ansible.builtin.shell:
      cmd: "systemctl enable --now code-server@{{ dev_username }}"
  - name: Set code-server password
    template:
        src: code-server-config.j2
        dest: "/home/{{ dev_username }}/.config/code-server/config.yaml"
        owner: "{{ dev_username }}"
        group: "{{ dev_username }}"
        mode: 0644
  - name: Enable code-server
    ansible.builtin.shell:
      cmd: "systemctl restart --now code-server@{{ dev_username }}"
  - name: Install Python
    dnf:
      name: python39
      state: latest
  - name: Install Python venv
    dnf:
      name: virtualenv
      state: latest
  - name: Install Podman
    dnf:
      name: podman
      state: latest
  - name: Login to Private Automation Hub registry
    ansible.builtin.shell:
      cmd: "podman login --tls-verify=false -u admin -p {{ registry_pw }} 192.168.1.36"
    become: yes
    become_user: "{{ dev_username }}"
  - name: Pull execution environments (cause navigator doesn't support --tls-verify=false)
    ansible.builtin.shell:
      cmd: "podman pull --tls-verify=false {{ item }}"
    become: yes
    become_user: "{{ dev_username }}"
    loop:
      - "192.168.1.36/win_ee"
      - "192.168.1.36/ee-supported-rhel8"
      - "192.168.1.36/ee-29-rhel8"
      - "192.168.1.36/ee-minimal-rhel8"
  - name: Install ansible-navigator
    pip:
      name: ansible-navigator
      state: present
  - name: Install ansible-navigator
    pip:
      name: ansible-builder
      state: present
  - name: Install ansible-galaxy
    pip:
      name: ansible-galaxy
      state: present
  - name: Install latest Git
    dnf:
      name: git
      state: latest
  - name: Apply Git config
    template:
      src: git-config.j2
      dest: "/home/{{ dev_username }}/.gitconfig"
      owner: "{{ dev_username }}"
      group: "{{ dev_username }}"
      mode: 0644
  - name: Clone ansible-demo project
    ansible.builtin.git:
      repo: https://{{ the_secret | trim }}@github.com/forenkla/ansible-demo.git
      dest: "/home/{{ dev_username }}/projects/ansible-demo"
    become: yes
    become_user: "{{ dev_username }}"
  - name: Clone ansible-ee project
    ansible.builtin.git:
      repo: https://{{ the_secret | trim }}@github.com/forenkla/ansible-ee.git
      dest: /home/{{ dev_username }}/projects/ansible-ee
    become: yes
    become_user: "{{ dev_username }}"
  - name: Clone ansible-config project
    ansible.builtin.git:
      repo: https://{{ the_secret | trim }}@github.com/forenkla/ansible-config.git
      dest: "/home/{{ dev_username }}/projects/ansible-config"
    become: yes
    become_user: "{{ dev_username }}"
  - name: Paste into to Terminal for access via http://localhost:8080
    ansible.builtin.debug:
      msg: "ssh -N -L 8080:127.0.0.1:8080 {{ dev_username }}@{{ centos_clone_ip }}"
