---
- name: Install code-server, setup Git
  hosts: centos-stream-template-clone
  become: yes
  gather_facts: false
  vars:
    the_secret: !vault |
                $ANSIBLE_VAULT;1.1;AES256
                33376537353436386161653735313961633334326138386563313433343963343332653562653934
                3461613838343433386264396233663331363137376235660a303063666464343063663634323735
                64656431326239326163643766363061613533343134643335623135623664616232393835353765
                3430383538343165350a653938616663633236376231383562666665303636343230613636663633
                38323636383637646239373236633963333434313930316538393962366132366363363534393732
                6634653863346565643062386437643936376465663534393438
  tasks:
  - name: Add the user 'jboivie'
    ansible.builtin.user:
      name: jboivie
      comment: Jens B
      groups: wheel
      password: "{{ requested_password|password_hash('sha512') }}"
  - name: Create projects directory
    ansible.builtin.file:
      path: /home/jboivie/projects
      state: directory
      owner: jboivie
      mode: '0755'
  - name: Download and Install code-server
    ansible.builtin.shell:
      cmd: curl -fsSL https://code-server.dev/install.sh | sh
  - name: Enable code-server
    ansible.builtin.shell:
      cmd: systemctl enable --now code-server@jboivie
  - name: Set code-server password
    template:
        src: code-server-config.j2
        dest: /home/jboivie/.config/code-server/config.yaml
        owner: jboivie
        group: jboivie
        mode: 0644
  - name: Enable code-server
    ansible.builtin.shell:
      cmd: systemctl restart --now code-server@jboivie
  - name: Install Python
    dnf:
      name: python39
      state: latest
  - name: Install Python venv
    dnf:
      name: virtualenv
      state: latest
  - name: Install Podman
    dnf:
      name: podman
      state: latest
  - name: Install ansible-navigator
    pip:
      name: ansible-navigator
      state: present
  - name: Install ansible-navigator
    pip:
      name: ansible-builder
      state: present
  - name: Install latest Git
    dnf:
      name: git
      state: latest
  - name: Apply Git config
    template:
      src: git-config.j2
      dest: /home/jboivie/.gitconfig
      owner: jboivie
      group: jboivie
      mode: 0644
  - name: Clone ansible-demo project
    ansible.builtin.git:
      repo: https://{{ the_secret | trim }}@github.com/forenkla/ansible-demo.git
      dest: /home/jboivie/projects/ansible-demo
    become: yes
    become_user: jboivie
  - name: Clone ansible-ee project
    ansible.builtin.git:
      repo: https://{{ the_secret | trim }}@github.com/forenkla/ansible-ee.git
      dest: /home/jboivie/projects/ansible-ee
    become: yes
    become_user: jboivie
  - name: Paste into to Terminal for access via http://localhost:8080
    ansible.builtin.debug:
      msg: "ssh -N -L 8080:127.0.0.1:8080 jboivie@{{ centos_clone_ip }}"
