---
- name: Stop and delete CentOS VM for dev environment
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: "Shutdown the {{ centos_hostname }} VM"
    ansible.builtin.shell:
      cmd: "/usr/local/bin/prlctl stop {{ centos_hostname }}"
  - name: Delete the new VM
    ansible.builtin.shell:
      cmd: "/usr/local/bin/prlctl delete {{ centos_hostname }}"
