---
- name: Stop and delete CentOS VM for dev environment
  hosts: MacBook-Pro
  become: no
  gather_facts: false

  tasks:
  - name: Shutdown the "centos-stream-template-clone" VM
    ansible.builtin.shell:
      cmd: /usr/local/bin/prlctl stop centos-stream-template-clone
  - name: Start the new VM
    ansible.builtin.shell:
      cmd: /usr/local/bin/prlctl delete centos-stream-template-clone
