---
- name: Setup ansible-demo project to controller
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_prompt:
    - name: node2_ip
      prompt: Enter IP of node2 (for Wrap up exercise)
      private: no
      
  tasks:
  - name: Setup Workshop Project
    awx.awx.project:
      name: "Workshop Project"
      organization: Default
      default_environment: "Default execution environment"
      state: present
      scm_type: git
      scm_url: https://github.com/ansible/workshop-examples.git
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes

  - name: Add Job Template Install Apache
    awx.awx.job_template:
      name: "Install Apache"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      execution_environment: "Default execution environment"
      playbook: rhel/apache/apache_install.yml
      project: "Workshop Project"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes

  - name: Add Job Template Create index.html
    awx.awx.job_template:
      name: "Create index.html"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      playbook: rhel/apache/apache_role_install.yml
      project: "Workshop Project"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes
      survey_enabled: yes
      survey_spec: "{{ lookup('file', 'survey.json') }}"

  - name: Add user Werner Web
    awx.awx.user:
      username: wweb
      password: ansible
      email: wweb@example.com
      first_name: Werner
      last_name: Web
      is_superuser: no
      is_system_auditor: no
      state: present

  - name: Add Joe to multiple job templates and a workflow
    awx.awx.role:
      user: wweb
      role: execute
      job_templates:
        - "Create index.html"
      state: present

  - name: Setup Webops Git Repo
    awx.awx.project:
      name: "Webops Git Repo"
      organization: Default
      default_environment: "Default execution environment"
      state: present
      scm_type: git
      scm_url: https://github.com/ansible/workshop-examples.git
      scm_branch: webops
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes

  - name: Setup Webdev Git Repo
    awx.awx.project:
      name: "Webdev Git Repo"
      organization: Default
      default_environment: "Default execution environment"
      state: present
      scm_type: git
      scm_url: https://github.com/ansible/workshop-examples.git
      scm_branch: webdev
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes

  - name: Add Job Template Web App Deploy
    awx.awx.job_template:
      name: "Web App Deploy"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      execution_environment: "Default execution environment"
      playbook: rhel/webops/web_infrastructure.yml
      project: "Webops Git Repo"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes

  - name: Add Job Template Node.js Deploy
    awx.awx.job_template:
      name: "Node.js Deploy"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      execution_environment: "Default execution environment"
      playbook: rhel/webdev/install_node_app.yml
      project: "Webdev Git Repo"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes

  - name: Setup Workflow Deploy Webapp Server
    awx.awx.workflow_job_template:
      name: Deploy Webapp Server
      schema:
        - identifier: node101
          unified_job_template:
            name: "Web App Deploy"
            inventory:
              organization:
                name: Default
            type: inventory_source
          related:
            success_nodes:
              - identifier: node201
            failure_nodes: []
            always_nodes: []
            credentials: []
        - identifier: node201
          unified_job_template:
            organization:
              name: Default
            name: "Node.js Deploy"
            type: job_template
          credentials: []
          related:
            success_nodes: []
            failure_nodes: []
            always_nodes: []
            credentials: []
            
  - name: Add group Webserver with stage dev variable
    awx.awx.group:
      name: Webserver
      description: "Webserver group"
      inventory: "Workshop Inventory"
      state: present
      variables:
        stage: dev
      hosts:
        - node1
        - node2
        - node3

  - name: Add host node2 with stage prod variable
    awx.awx.host:
      name: node2
      description: "imported"
      inventory: "Workshop Inventory"
      state: present
      variables:
        ansible_host: "{{ node2_ip }}"
        stage: prod

  - name: Add Job Template Create Web Content
    awx.awx.job_template:
      name: "Create Web Content"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      execution_environment: "Default execution environment"
      playbook: rhel/apache/webcontent.yml
      project: "Workshop Project"
      credential: "Workshop Credential"
      become_enabled: yes
      survey_enabled: yes
      survey_spec: "{{ lookup('file', 'survey2.json') }}"
      extra_vars:
        dev_content: "default dev content"
        prod_content: "default prod content"
