---
- name: Setup ansible-demo project to controller
  hosts: localhost
  become: false
  gather_facts: false
  
  tasks:
  - name: Setup Workshop Project
    awx.awx.project:
      name: "Workshop Project"
      organization: Default
      default_environment: "Default execution environment"
      state: present
      scm_update_on_launch: True
      scm_delete_on_update: True
      scm_type: git
      scm_url: https://github.com/ansible/workshop-examples.git
      scm_clean: yes
      scm_delete_on_update: yes
      scm_update_on_launch: yes
      
  - name: Add Job Template Install Apache
    awx.awx.job_template:
      name: "Install Apache"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      execution_environment: "Default execution environment"
      playbook: rhel/apache/apache_install.yml
      project: "Workshop Project"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes

  - name: Add Job Template Create index.html
    awx.awx.job_template:
      name: "Create index.html"
      organization: Default
      state: present
      inventory: "Workshop Inventory"
      playbook: rhel/apache/apache_role_install.yml
      project: "Workshop Project"
      credential: "Workshop Credential"
      limit: web
      become_enabled: yes
      survey_enabled: yes
      survey_spec: "{{ lookup('file', 'survey.json') }}"
      
  - name: Add user Werner Web
    awx.awx.user:
      username: wweb
      password: ansible
      email: wweb@example.com
      first_name: Werner
      last_name: Web
      is_superuser: no
      is_system_auditor: no
      state: present
      
  - name: Add Joe to multiple job templates and a workflow
    role:
      user: wweb
      role:
        - read
        - execute
      job_templates:
        - "Create index.html"
      state: present

