---
- name: Setup ansible-demo project to controller
  hosts: localhost
  become: false

  tasks:
  - name: Add Win_EE execution environment to ansible_navigator
    blockinfile:
      path: ~/.ansible-navigator.yml
      block: |2
          execution-environment:
            image: quay.io/jboivie/win_ee:latest
            enabled: true
            container-engine: podman
            pull-policy: missing
            volume-mounts:
            - src: "/etc/ansible/"
              dest: "/etc/ansible/"
            - src: "/tmp/rhel/"
              dest: "/tmp/rhel/"
