---
- name: Setup ansible-demo project to controller
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_prompt:
    - name: win_username
      prompt: Enter username for Windows host
    - name: win_password
      prompt: Enter password for Windows host
      
  tasks:
  - name: Add Windows credentials
    awx.awx.credential:
      name: Windows credentials
      credential_type: Machine
      organization: Default
      inputs:
        username: {{ win_username }}
        password: {{ win_password }}
      
  - name: Add EE to controller
    awx.awx.execution_environment:
      name: "Win EE"
      image: quay.io/jboivie/win_ee:latest
      
  - name: AWX Project
    awx.awx.project:
      name: ansible-demo
      organization: Default
      default_environment: "Win EE"
      state: present
      scm_update_on_launch: True
      scm_delete_on_update: True
      scm_type: git
      scm_url: https://github.com/forenkla/ansible-demo.git
      
